import MLPredictions from '../components/MLPredictions';
import { FaBrain } from 'react-icons/fa';

export default function MLPage() {
  return (
    <div style={s.page}>
      <div style={s.header}>
        <div style={s.iconWrap}>
          <FaBrain style={{ color: '#7c5cfc', fontSize: '28px' }} />
        </div>
        <p style={s.label}>MACHINE LEARNING ENGINE</p>
        <h1 style={s.title}>AI Risk Predictions</h1>
        <p style={s.sub}>
          Risk scores generated by a Random Forest model trained on live crisis data.
          Scores update every time new events are fetched.
        </p>
      </div>
      <MLPredictions />
    </div>
  );
}

const s = {
  page:    { minHeight: '100vh', background: '#04080f', color: '#e8f4ff', fontFamily: "'Inter', sans-serif", maxWidth: '1200px', margin: '0 auto', padding: '48px 28px' },
  header:  { textAlign: 'center', marginBottom: '48px' },
  iconWrap:{ display: 'inline-flex', padding: '18px', background: 'rgba(124,92,252,0.1)', border: '1px solid rgba(124,92,252,0.2)', borderRadius: '18px', marginBottom: '16px' },
  label:   { fontSize: '10px', color: '#7c5cfc', letterSpacing: '4px', margin: '0 0 10px', fontFamily: "'JetBrains Mono', monospace", fontWeight: '700' },
  title:   { fontSize: 'clamp(28px,4vw,44px)', fontWeight: '800', margin: '0 0 14px', fontFamily: "'Space Grotesk', sans-serif", letterSpacing: '-1.5px', background: 'linear-gradient(135deg,#e8f4ff,#7c5cfc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' },
  sub:     { fontSize: '15px', color: '#3d6080', lineHeight: 1.8, maxWidth: '560px', margin: '0 auto' },
};